use std::collections::HashMap;

use crate::ast::*;

// ── Runtime preamble injected at the top of every generated file ──────────────

const PREAMBLE: &str = r#"// Generated by oogac — the Ooga Booga compiler
#![allow(non_snake_case, unused_variables, dead_code, unused_mut, unused_imports)]

fn WORDY(x: impl std::fmt::Display) -> String {
    x.to_string()
}
fn NUMBR(x: impl AsRef<str>) -> i32 {
    x.as_ref().trim().parse().expect("UGH! CAVE NUMBR FAIL. NOT A ROCK NUMBER.")
}
fn NUMBR_BIG(x: impl AsRef<str>) -> i64 {
    x.as_ref().trim().parse().expect("UGH! CAVE NUMBR_BIG FAIL. NOT A BIG ROCK NUMBER.")
}
fn NUMBR_DRIP(x: impl AsRef<str>) -> f64 {
    x.as_ref().trim().parse().expect("UGH! CAVE NUMBR_DRIP FAIL. NOT A DRIP NUMBER.")
}
fn BIGNESS(x: impl AsRef<str>) -> i64 {
    x.as_ref().len() as i64
}
fn FLOORY(x: f64) -> f64 { x.floor() }
fn ROUNDY(x: f64) -> f64 { x.round() }
fn ROOTY(x: f64) -> f64  { x.sqrt()  }
fn __ooga_concat(a: impl std::fmt::Display, b: impl std::fmt::Display) -> String {
    format!("{}{}", a, b)
}

"#;

// ── Code generator ────────────────────────────────────────────────────────────

pub struct Codegen {
    output: String,
    indent: usize,
    /// Variable → type map for PLUS string-detection heuristic.
    type_env: HashMap<String, TypeAnnotation>,
}

impl Default for Codegen {
    fn default() -> Self {
        Self::new()
    }
}

impl Codegen {
    pub fn new() -> Self {
        Codegen {
            output: String::new(),
            indent: 0,
            type_env: HashMap::new(),
        }
    }

    pub fn generate(mut self, program: &Program) -> String {
        self.output.push_str(PREAMBLE);

        // First pass: collect all top-level variable types.
        for stmt in &program.statements {
            self.collect_types(stmt);
        }

        // Emit function definitions first (they live outside main).
        for stmt in &program.statements {
            if matches!(stmt, Statement::FuncDef { .. }) {
                self.emit_statement(stmt);
                self.output.push('\n');
            }
        }

        // Wrap remaining top-level statements in fn main().
        let has_top_level = program
            .statements
            .iter()
            .any(|s| !matches!(s, Statement::FuncDef { .. }));

        if has_top_level {
            self.output.push_str("fn main() {\n");
            self.indent = 1;
            for stmt in &program.statements {
                if !matches!(stmt, Statement::FuncDef { .. }) {
                    self.emit_statement(stmt);
                }
            }
            self.indent = 0;
            self.output.push_str("}\n");
        }

        self.output
    }

    // ── Type collection pass ──────────────────────────────────────────────

    fn collect_types(&mut self, stmt: &Statement) {
        match stmt {
            Statement::VarDecl { name, type_ann, .. } => {
                self.type_env.insert(name.clone(), type_ann.clone());
            }
            Statement::FuncDef { params, body, .. } => {
                for (pname, ptype) in params {
                    self.type_env.insert(pname.clone(), ptype.clone());
                }
                for s in body {
                    self.collect_types(s);
                }
            }
            Statement::If {
                then_block,
                else_ifs,
                else_block,
                ..
            } => {
                for s in then_block {
                    self.collect_types(s);
                }
                for (_, block) in else_ifs {
                    for s in block {
                        self.collect_types(s);
                    }
                }
                if let Some(block) = else_block {
                    for s in block {
                        self.collect_types(s);
                    }
                }
            }
            Statement::While { body, .. } | Statement::Loop { body, .. } => {
                for s in body {
                    self.collect_types(s);
                }
            }
            _ => {}
        }
    }

    // ── Statement emission ────────────────────────────────────────────────

    fn emit_statement(&mut self, stmt: &Statement) {
        match stmt {
            Statement::VarDecl {
                name,
                type_ann,
                initializer,
                ..
            } => {
                self.push_indent();
                self.output.push_str("let mut ");
                self.output.push_str(name);
                self.output.push_str(": ");
                self.output.push_str(type_ann.to_rust());
                self.output.push_str(" = ");
                if let Some(init) = initializer {
                    self.emit_expr_for_type(init, type_ann);
                } else {
                    self.output.push_str(type_ann.default_value());
                }
                self.output.push_str(";\n");
            }

            Statement::Assign { name, value, .. } => {
                self.push_indent();
                self.output.push_str(name);
                self.output.push_str(" = ");
                // Look up type for potential .to_string() coercion
                let ty = self.type_env.get(name).cloned();
                if let Some(t) = &ty {
                    self.emit_expr_for_type(value, t);
                } else {
                    self.emit_expr(value);
                }
                self.output.push_str(";\n");
            }

            Statement::Say { value, .. } => {
                self.push_indent();
                self.output.push_str("println!(\"{}\", ");
                self.emit_expr(value);
                self.output.push_str(");\n");
            }

            Statement::Hear { name, .. } => {
                self.push_indent();
                self.output.push_str("{\n");
                self.indent += 1;
                self.push_indent();
                self.output
                    .push_str("let mut __ooga_input = String::new();\n");
                self.push_indent();
                self.output.push_str("std::io::stdin().read_line(&mut __ooga_input).expect(\"UGH! CAVE EAR BROKEN\");\n");
                self.push_indent();
                self.output.push_str(name);
                self.output
                    .push_str(" = __ooga_input.trim().to_string();\n");
                self.indent -= 1;
                self.push_indent();
                self.output.push_str("}\n");
            }

            Statement::If {
                condition,
                then_block,
                else_ifs,
                else_block,
                ..
            } => {
                self.push_indent();
                self.output.push_str("if ");
                self.emit_expr(condition);
                self.output.push_str(" {\n");
                self.indent += 1;
                for s in then_block {
                    self.emit_statement(s);
                }
                self.indent -= 1;
                self.push_indent();
                self.output.push('}');

                for (cond, block) in else_ifs {
                    self.output.push_str(" else if ");
                    self.emit_expr(cond);
                    self.output.push_str(" {\n");
                    self.indent += 1;
                    for s in block {
                        self.emit_statement(s);
                    }
                    self.indent -= 1;
                    self.push_indent();
                    self.output.push('}');
                }

                if let Some(block) = else_block {
                    self.output.push_str(" else {\n");
                    self.indent += 1;
                    for s in block {
                        self.emit_statement(s);
                    }
                    self.indent -= 1;
                    self.push_indent();
                    self.output.push('}');
                }
                self.output.push('\n');
            }

            Statement::While {
                condition, body, ..
            } => {
                self.push_indent();
                self.output.push_str("while ");
                self.emit_expr(condition);
                self.output.push_str(" {\n");
                self.indent += 1;
                for s in body {
                    self.emit_statement(s);
                }
                self.indent -= 1;
                self.push_indent();
                self.output.push_str("}\n");
            }

            Statement::Loop { body, .. } => {
                self.push_indent();
                self.output.push_str("loop {\n");
                self.indent += 1;
                for s in body {
                    self.emit_statement(s);
                }
                self.indent -= 1;
                self.push_indent();
                self.output.push_str("}\n");
            }

            Statement::Break { .. } => {
                self.push_indent();
                self.output.push_str("break;\n");
            }

            Statement::Continue { .. } => {
                self.push_indent();
                self.output.push_str("continue;\n");
            }

            Statement::FuncDef {
                name,
                params,
                return_type,
                body,
                ..
            } => {
                self.push_indent();
                self.output.push_str("fn ");
                self.output.push_str(name);
                self.output.push('(');
                for (i, (pname, ptype)) in params.iter().enumerate() {
                    if i > 0 {
                        self.output.push_str(", ");
                    }
                    self.output.push_str(pname);
                    self.output.push_str(": ");
                    self.output.push_str(ptype.to_rust());
                }
                self.output.push(')');
                if !matches!(return_type, TypeAnnotation::Nothing) {
                    self.output.push_str(" -> ");
                    self.output.push_str(return_type.to_rust());
                }
                self.output.push_str(" {\n");
                self.indent += 1;
                for (pname, ptype) in params {
                    self.type_env.insert(pname.clone(), ptype.clone());
                }
                for s in body {
                    self.emit_statement(s);
                }
                self.indent -= 1;
                self.push_indent();
                self.output.push_str("}\n");
            }

            Statement::Return { value, .. } => {
                self.push_indent();
                if let Some(val) = value {
                    self.output.push_str("return ");
                    self.emit_expr(val);
                    self.output.push_str(";\n");
                } else {
                    self.output.push_str("return;\n");
                }
            }

            Statement::ExprStmt { expr, .. } => {
                self.push_indent();
                self.emit_expr(expr);
                self.output.push_str(";\n");
            }
        }
    }

    // ── Expression emission ───────────────────────────────────────────────

    /// Emit an expression, adding `.to_string()` when the target type is WORDS
    /// and the source is a string literal (so `let x: String = "hi".to_string();`).
    fn emit_expr_for_type(&mut self, expr: &Expr, ty: &TypeAnnotation) {
        if ty.is_words() {
            if let Expr::Literal {
                value: Literal::Str(_),
                ..
            } = expr
            {
                self.emit_expr(expr);
                self.output.push_str(".to_string()");
                return;
            }
        }
        self.emit_expr(expr);
    }

    fn emit_expr(&mut self, expr: &Expr) {
        match expr {
            Expr::Literal { value, .. } => match value {
                Literal::Int(n) => self.output.push_str(&n.to_string()),
                Literal::Float(f) => {
                    let s = format!("{}", f);
                    self.output.push_str(&s);
                    if !s.contains('.') && !s.contains('e') && !s.contains('E') {
                        self.output.push_str(".0");
                    }
                }
                Literal::Str(s) => {
                    self.output.push('"');
                    for ch in s.chars() {
                        match ch {
                            '"' => self.output.push_str("\\\""),
                            '\\' => self.output.push_str("\\\\"),
                            '\n' => self.output.push_str("\\n"),
                            '\t' => self.output.push_str("\\t"),
                            other => self.output.push(other),
                        }
                    }
                    self.output.push('"');
                }
                Literal::Bool(b) => self.output.push_str(if *b { "true" } else { "false" }),
            },

            Expr::Ident { name, .. } => {
                self.output.push_str(name);
            }

            Expr::BinOp {
                op, left, right, ..
            } => {
                if *op == BinOp::Plus && self.expr_is_words(left, right) {
                    self.output.push_str("__ooga_concat(");
                    self.emit_expr(left);
                    self.output.push_str(", ");
                    self.emit_expr(right);
                    self.output.push(')');
                } else {
                    self.output.push('(');
                    self.emit_expr(left);
                    self.output.push(' ');
                    self.output.push_str(binop_to_rust(op));
                    self.output.push(' ');
                    self.emit_expr(right);
                    self.output.push(')');
                }
            }

            Expr::UnaryOp { op, operand, .. } => {
                match op {
                    UnaryOp::Neg => self.output.push('-'),
                    UnaryOp::Not => self.output.push('!'),
                }
                self.output.push('(');
                self.emit_expr(operand);
                self.output.push(')');
            }

            Expr::FuncCall { name, args, .. } => {
                self.output.push_str(name);
                self.output.push('(');
                for (i, arg) in args.iter().enumerate() {
                    if i > 0 {
                        self.output.push_str(", ");
                    }
                    self.emit_expr(arg);
                }
                self.output.push(')');
            }
        }
    }

    /// Returns true if either operand looks like a String (for PLUS → concat).
    fn expr_is_words(&self, left: &Expr, right: &Expr) -> bool {
        self.single_is_words(left) || self.single_is_words(right)
    }

    fn single_is_words(&self, expr: &Expr) -> bool {
        match expr {
            Expr::Literal {
                value: Literal::Str(_),
                ..
            } => true,
            Expr::Ident { name, .. } => {
                matches!(self.type_env.get(name), Some(TypeAnnotation::Words))
            }
            Expr::FuncCall { name, .. } if name == "__ooga_concat" || name == "WORDY" => true,
            Expr::BinOp {
                op: BinOp::Plus,
                left,
                right,
                ..
            } => self.expr_is_words(left, right),
            _ => false,
        }
    }

    fn push_indent(&mut self) {
        for _ in 0..self.indent {
            self.output.push_str("    ");
        }
    }
}

fn binop_to_rust(op: &BinOp) -> &'static str {
    match op {
        BinOp::Plus => "+",
        BinOp::Minus => "-",
        BinOp::Times => "*",
        BinOp::Divvy => "/",
        BinOp::Mod => "%",
        BinOp::Is => "==",
        BinOp::Isnt => "!=",
        BinOp::Biggr => ">",
        BinOp::Smallr => "<",
        BinOp::BiggrIs => ">=",
        BinOp::SmallrIs => "<=",
        BinOp::And => "&&",
        BinOp::Or => "||",
    }
}

// ── Tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crate::lexer::Lexer;
    use crate::parser::Parser;

    fn compile(src: &str) -> String {
        let tokens = Lexer::new(src).tokenise().expect("lex");
        let program = Parser::new(tokens).parse_program().expect("parse");
        Codegen::new().generate(&program)
    }

    #[test]
    fn test_hello_world_output() {
        let rs = compile(r#"SAY "hello, cave!""#);
        assert!(rs.contains("println!("), "expected println!: {}", rs);
    }

    #[test]
    fn test_var_decl_no_init() {
        let rs = compile("OOGA x: ROCK");
        assert!(rs.contains("let mut x: i32 = 0;"), "got: {}", rs);
    }

    #[test]
    fn test_var_decl_with_init() {
        let rs = compile("OOGA count: ROCK BE 0");
        assert!(rs.contains("let mut count: i32 = 0;"), "got: {}", rs);
    }

    #[test]
    fn test_assignment() {
        let rs = compile("OOGA x: ROCK BE 1\nx GETS 2");
        assert!(rs.contains("x = 2;"), "got: {}", rs);
    }

    #[test]
    fn test_while_loop() {
        let rs = compile("OOGA i: ROCK BE 0\nUGGA WHILE i SMALLR IS 5\ni GETS i PLUS 1\nUGHA");
        assert!(rs.contains("while "), "got: {}", rs);
    }

    #[test]
    fn test_func_def_emitted_before_main() {
        let rs = compile("MAGIC double(n: ROCK) -> ROCK\nGIVEBACK n TIMES 2\nUGHA\nSAY double(4)");
        let func_pos = rs.find("fn double").expect("no fn double");
        let main_pos = rs.find("fn main").expect("no fn main");
        assert!(func_pos < main_pos, "function should be before main");
    }

    #[test]
    fn test_type_annotations_emitted() {
        let rs = compile("MAGIC add(a: ROCK, b: BIGROCK) -> BIGROCK\nGIVEBACK a PLUS b\nUGHA");
        assert!(rs.contains("fn add(a: i32, b: i64) -> i64"), "got: {}", rs);
    }

    #[test]
    fn test_words_var() {
        let rs = compile(r#"OOGA s: WORDS BE "cave""#);
        assert!(rs.contains("let mut s: String"), "got: {}", rs);
    }

    #[test]
    fn test_if_else_emitted() {
        let rs = compile("OOGA x: ROCK BE 5\nIFF x BIGGR 3\nSAY x\nNOPE\nSAY 0\nUGHA");
        assert!(rs.contains("if ") && rs.contains("} else {"), "got: {}", rs);
    }

    #[test]
    fn test_loop_break_emitted() {
        let rs =
            compile("OOGA i: ROCK BE 0\nUGGA DO\ni GETS i PLUS 1\nIFF i IS 3\nSTOP\nUGHA\nUGHA");
        assert!(
            rs.contains("loop {") && rs.contains("break;"),
            "got: {}",
            rs
        );
    }

    #[test]
    fn test_preamble_has_helpers() {
        let rs = compile("SAY 1");
        assert!(rs.contains("fn WORDY"), "got: {}", rs);
        assert!(rs.contains("fn NUMBR"), "got: {}", rs);
        assert!(rs.contains("fn __ooga_concat"), "got: {}", rs);
    }
}
