use crate::ast::*;

// ── Runtime preamble injected at the top of every generated file ──────────────

const PREAMBLE: &str = r#"// Generated by oogac — the Ooga Booga compiler
// Run with: node output.js
"use strict";

// ── Built-in functions ────────────────────────────────────────────────────────
function NUMBR(x)   { return Number(x); }
function WORDY(x)   { return String(x); }
function BIGNESS(x) { return x.length; }
function FLOORY(x)  { return Math.floor(x); }
function ROUNDY(x)  { return Math.round(x); }
function ROOTY(x)   { return Math.sqrt(x); }

// ── I/O helpers ───────────────────────────────────────────────────────────────
let _readline;
function _hear() {
  if (!_readline) {
    // Try readline-sync for synchronous stdin; fall back to a stub.
    try {
      _readline = require("readline-sync");
    } catch (_) {
      _readline = { question: (_p) => { throw new Error("UGH! CAVE NEEDS readline-sync TO HEAR. RUN: npm install readline-sync"); } };
    }
  }
  return _readline.question("");
}

"#;

// ── Code generator ────────────────────────────────────────────────────────────

pub struct Codegen {
    output: String,
    indent: usize,
}

impl Codegen {
    pub fn new() -> Self {
        Codegen {
            output: String::new(),
            indent: 0,
        }
    }

    pub fn generate(mut self, program: &Program) -> String {
        self.output.push_str(PREAMBLE);

        // Emit function definitions first (hoisting into top-level scope).
        for stmt in &program.statements {
            if matches!(stmt, Statement::FuncDef { .. }) {
                self.emit_statement(stmt);
                self.output.push('\n');
            }
        }

        // Emit the rest of the statements.
        for stmt in &program.statements {
            if !matches!(stmt, Statement::FuncDef { .. }) {
                self.emit_statement(stmt);
            }
        }

        self.output
    }

    // ── Statement emission ────────────────────────────────────────────────

    fn emit_statement(&mut self, stmt: &Statement) {
        match stmt {
            Statement::VarDecl {
                name, initializer, ..
            } => {
                self.indent();
                self.output.push_str("let ");
                self.output.push_str(name);
                if let Some(init) = initializer {
                    self.output.push_str(" = ");
                    self.emit_expr(init);
                } else {
                    self.output.push_str(" = null");
                }
                self.output.push_str(";\n");
            }

            Statement::Assign { name, value, .. } => {
                self.indent();
                self.output.push_str(name);
                self.output.push_str(" = ");
                self.emit_expr(value);
                self.output.push_str(";\n");
            }

            Statement::Say { value, .. } => {
                self.indent();
                self.output.push_str("console.log(");
                self.emit_expr(value);
                self.output.push_str(");\n");
            }

            Statement::Hear { name, .. } => {
                self.indent();
                self.output.push_str(name);
                self.output.push_str(" = _hear();\n");
            }

            Statement::If {
                condition,
                then_block,
                else_ifs,
                else_block,
                ..
            } => {
                self.indent();
                self.output.push_str("if (");
                self.emit_expr(condition);
                self.output.push_str(") {\n");
                self.indent += 1;
                for s in then_block {
                    self.emit_statement(s);
                }
                self.indent -= 1;
                self.indent();
                self.output.push('}');

                for (cond, block) in else_ifs {
                    self.output.push_str(" else if (");
                    self.emit_expr(cond);
                    self.output.push_str(") {\n");
                    self.indent += 1;
                    for s in block {
                        self.emit_statement(s);
                    }
                    self.indent -= 1;
                    self.indent();
                    self.output.push('}');
                }

                if let Some(block) = else_block {
                    self.output.push_str(" else {\n");
                    self.indent += 1;
                    for s in block {
                        self.emit_statement(s);
                    }
                    self.indent -= 1;
                    self.indent();
                    self.output.push('}');
                }
                self.output.push('\n');
            }

            Statement::While {
                condition, body, ..
            } => {
                self.indent();
                self.output.push_str("while (");
                self.emit_expr(condition);
                self.output.push_str(") {\n");
                self.indent += 1;
                for s in body {
                    self.emit_statement(s);
                }
                self.indent -= 1;
                self.indent();
                self.output.push_str("}\n");
            }

            Statement::Loop { body, .. } => {
                self.indent();
                self.output.push_str("while (true) {\n");
                self.indent += 1;
                for s in body {
                    self.emit_statement(s);
                }
                self.indent -= 1;
                self.indent();
                self.output.push_str("}\n");
            }

            Statement::Break { .. } => {
                self.indent();
                self.output.push_str("break;\n");
            }

            Statement::Continue { .. } => {
                self.indent();
                self.output.push_str("continue;\n");
            }

            Statement::FuncDef {
                name, params, body, ..
            } => {
                self.indent();
                self.output.push_str("function ");
                self.output.push_str(name);
                self.output.push('(');
                self.output.push_str(&params.join(", "));
                self.output.push_str(") {\n");
                self.indent += 1;
                for s in body {
                    self.emit_statement(s);
                }
                self.indent -= 1;
                self.indent();
                self.output.push_str("}\n");
            }

            Statement::Return { value, .. } => {
                self.indent();
                self.output.push_str("return");
                if let Some(val) = value {
                    self.output.push(' ');
                    self.emit_expr(val);
                }
                self.output.push_str(";\n");
            }

            Statement::ExprStmt { expr, .. } => {
                self.indent();
                self.emit_expr(expr);
                self.output.push_str(";\n");
            }
        }
    }

    // ── Expression emission ───────────────────────────────────────────────

    fn emit_expr(&mut self, expr: &Expr) {
        match expr {
            Expr::Literal { value, .. } => match value {
                Literal::Int(n) => self.output.push_str(&n.to_string()),
                Literal::Float(f) => {
                    // Ensure the float always has a decimal point in JS output.
                    let s = format!("{}", f);
                    if s.contains('.') {
                        self.output.push_str(&s);
                    } else {
                        self.output.push_str(&s);
                        self.output.push_str(".0");
                    }
                }
                Literal::Str(s) => {
                    self.output.push('"');
                    // Escape special chars in the generated string.
                    for ch in s.chars() {
                        match ch {
                            '"' => self.output.push_str("\\\""),
                            '\\' => self.output.push_str("\\\\"),
                            '\n' => self.output.push_str("\\n"),
                            '\t' => self.output.push_str("\\t"),
                            other => self.output.push(other),
                        }
                    }
                    self.output.push('"');
                }
                Literal::Bool(b) => self.output.push_str(if *b { "true" } else { "false" }),
                Literal::Void => self.output.push_str("null"),
            },

            Expr::Ident { name, .. } => {
                self.output.push_str(name);
            }

            Expr::BinOp {
                op, left, right, ..
            } => {
                self.output.push('(');
                self.emit_expr(left);
                self.output.push(' ');
                self.output.push_str(binop_to_js(op));
                self.output.push(' ');
                self.emit_expr(right);
                self.output.push(')');
            }

            Expr::UnaryOp { op, operand, .. } => {
                match op {
                    UnaryOp::Neg => self.output.push('-'),
                    UnaryOp::Not => self.output.push('!'),
                }
                self.output.push('(');
                self.emit_expr(operand);
                self.output.push(')');
            }

            Expr::FuncCall { name, args, .. } => {
                self.output.push_str(name);
                self.output.push('(');
                for (i, arg) in args.iter().enumerate() {
                    if i > 0 {
                        self.output.push_str(", ");
                    }
                    self.emit_expr(arg);
                }
                self.output.push(')');
            }
        }
    }

    fn indent(&mut self) {
        for _ in 0..self.indent {
            self.output.push_str("  ");
        }
    }
}

fn binop_to_js(op: &BinOp) -> &'static str {
    match op {
        BinOp::Plus => "+",
        BinOp::Minus => "-",
        BinOp::Times => "*",
        BinOp::Divvy => "/",
        BinOp::Mod => "%",
        BinOp::Is => "===",
        BinOp::Isnt => "!==",
        BinOp::Biggr => ">",
        BinOp::Smallr => "<",
        BinOp::BiggrIs => ">=",
        BinOp::SmallrIs => "<=",
        BinOp::And => "&&",
        BinOp::Or => "||",
    }
}

// ── Tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crate::lexer::Lexer;
    use crate::parser::Parser;

    fn compile(src: &str) -> String {
        let tokens = Lexer::new(src).tokenise().expect("lex");
        let program = Parser::new(tokens).parse_program().expect("parse");
        Codegen::new().generate(&program)
    }

    #[test]
    fn test_hello_world_output() {
        let js = compile(r#"SAY "hello, cave!""#);
        assert!(js.contains(r#"console.log("hello, cave!")"#));
    }

    #[test]
    fn test_var_decl_no_init() {
        let js = compile("OOGA x");
        assert!(js.contains("let x = null;"));
    }

    #[test]
    fn test_var_decl_with_init() {
        let js = compile("OOGA count BE 0");
        assert!(js.contains("let count = 0;"));
    }

    #[test]
    fn test_assignment() {
        let js = compile("OOGA x BE 1\nx GETS 2");
        assert!(js.contains("x = 2;"));
    }

    #[test]
    fn test_while_loop() {
        let js = compile("OOGA i BE 0\nUGGA WHILE i SMALLR 5\ni GETS i PLUS 1\nUGHA");
        assert!(js.contains("while ("));
        assert!(js.contains("i < 5"));
    }

    #[test]
    fn test_func_def_hoisted() {
        let js = compile("MAGIC double(n)\nGIVEBACK n TIMES 2\nUGHA\nSAY double(4)");
        // Function should appear before any console.log
        let func_pos = js.find("function double").expect("no function");
        let call_pos = js.find("console.log").expect("no console.log");
        assert!(
            func_pos < call_pos,
            "function should be hoisted before main code"
        );
    }

    #[test]
    fn test_if_else() {
        let js = compile("OOGA x BE 1\nIFF x IS 1\nSAY \"yes\"\nNOPE\nSAY \"no\"\nUGHA");
        assert!(js.contains("if ("));
        assert!(js.contains("} else {"));
    }

    #[test]
    fn test_boolean_literals() {
        let js = compile(r#"SAY YEAH"#);
        assert!(js.contains("console.log(true)"));
    }

    #[test]
    fn test_void_literal() {
        let js = compile("OOGA x BE VOID");
        assert!(js.contains("let x = null;"));
    }

    #[test]
    fn test_break_continue() {
        let js = compile("UGGA DO\nSTOP\nUGHA");
        assert!(js.contains("break;"));
    }
}
